### ISSUE TITLE
Cannot get it working on Win10, Code 1.19.3, x64. Plugin version 0.2.0

### ISSUE THREAD

**Issue by ondrique** [ecmel/vscode-html-css#58]
Hi,

thank you for a great plugin, I have been using it for a while!

**Problem:**

- Yesterday, I moved to a new Win10 machine and I can't get it working. That means the plugin does not pick local scss nor external stylesheet and does not show them after ctrl+ space. I work in Jade mostly but tried also HTML.
- Project and settings are exactly the same as on my old machine where it works like a charm. The only difference is that I was running 32bit install of Code and now I have the 64bit version.

**Solutions I tried:**

I tried literally everything I could think of:  
- disable other plugins
- reinstall plugin
- reinstall VS code - tried both 32 bit and 64 bit again 😄 

Can you advise me what else could I try to get it working?

Thank you,

Ondrej

**Comment by ondrique** [comment]
Ok, I found out that there is also a developer tools console inside VS code 😄 and found the issue:

`Cannot find module 'vscode-languageserver-types'`

![image](https://user-images.githubusercontent.com/1532160/35818547-b100e9de-0aa0-11e8-91d7-502af0d08e7e.png)

**Comment by ondrique** [comment]
Solved, I am closing this. 🎉 

**Lessons learned:**

- After few reinstalls, the extension files on the HDD were from the first installation. So, some form caching takes place there.
- I checked the node_modules of the extension and vscode-languageserver-types was there, who knows why it was not loading it.
- I deleted the extension from the folder myself, installed it again in VS code and it's working now.
