### ISSUE TITLE
Intelisense Not Working

### ISSUE THREAD

**Issue by shiva-shankar22** [ecmel/vscode-html-css#269]
Type: <b>Feature Request</b>

I have been using this HTML CSS Support  extension  

Now this extension is not working while using bootstrap classes

Extension version: 1.13.1
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by ecmel** [comment]
Should work in 1.14.0

**Comment by dzpt** [comment]
none of them work on vscode 1.72.2.
2.*, 1.14, 1.13

local css, remote bootstrap css, won't work, installed `Zignd.html-css-class-completion` and it works

**Comment by compadrejunior** [comment]
Same problem here. Intellisense stopped working. No suggestions appear in HTML class attributes. I've checked all necessary the configuration, but the problem persists. The extension host log reports the following error message:

`[error] TypeError: e.replace is not a function
    at c:\Users\josec\.vscode\extensions\ecmel.vscode-html-css-2.0.9\dist\extension.js:1:2817
    at Array.map (<anonymous>)`
 
My VSCode version:

`Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621`

Other extensions aren't working as well.
